version: "3.9"

services:
  user_service:
    build: .
    container_name: user_service
    env_file:
      - .env.docker
    ports:
      - "8002:8000"
    depends_on:
      - db
    restart: always
    networks:
      - user_network

  db:
    image: postgres:15
    container_name: user_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pooja521689
      POSTGRES_DB: userdb
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - user_network
 
volumes:
  postgres_data:
 
networks:
  user_network:
